require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/inventories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Inventory. As you add validations to Inventory, be sure to
  # adjust the attributes here as well.
  fixtures :shoe_stores, :shoe_models
  
  let(:valid_attributes) {
    {shoe_store: shoe_stores(:one), shoe_model: shoe_models(:one), quantity: 10}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Inventory.create! valid_attributes
      get inventories_url
      expect(response).to be_successful
    end
  end

end
